version: '3.5'

services:
  server:
    image: node:10
    volumes:
    - ./server:/home/node/app
    working_dir: /home/node/app
    command: "yarn start"
    ports:
    - 4000:4000
    restart: on-failure
    depends_on:
    - catalog
    - cart
    networks:
      chili:

  catalog:
    image: node:10
    volumes:
    - ./catalog:/home/node/app
    working_dir: /home/node/app
    command: "yarn start"
    restart: on-failure
    environment:
      MONGO_HOST: mongo_catalog
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: topsecret
    depends_on:
    - mongo_catalog
    networks:
      chili:

  mongo_catalog:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: topsecret
    networks:
      chili:

  cart:
    image: node:10
    volumes:
    - ./cart:/home/node/app
    working_dir: /home/node/app
    command: "yarn start"
    restart: on-failure
    depends_on:
    - mongo_cart
    environment:
      MONGO_HOST: mongo_cart
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: topsecret
    networks:
      chili:

  mongo_cart:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: topsecret
    ports:
    -  27017:27017
    networks:
      chili:

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: topsecret
      ME_CONFIG_MONGODB_SERVER: mongo_cart
    networks:
      chili:

networks:
  chili: